### ISSUE TITLE
with_args unable to pass attribute as value

### ISSUE THREAD

**Issue by treydock** [has207/flexmock#103]
I am not sure why this is working differently.  I am still very new to Python unit testing and mocking so if this is the wrong approach then please advise.

Works:
```
flexmock(os.path).should_receive("isfile").with_args("/dh/dne/image.tiff").and_return(True)
```
Does not work:
```
flexmock(os.path).should_receive("isfile").with_args(job.page.image_path).and_return(True)
```
The time it does not work the error printed shows the value passed to "os.path.isfile" is the exact same as when it's passed as a string instead of a reference to the attribute:

```
>       raise MethodSignatureError(_format_args(name, arguments))
E       MethodSignatureError: isfile("/dh/dne/image.tiff")

../../.local/lib/python2.7/site-packages/flexmock.py:960: MethodSignatureError
```

Is this expected?  I was trying to move towards using py.test's tmpdir at which point the path would be somewhat unknown at runtime and so referencing it would have to be done using attributes.

**Comment by has207** [comment]
Hmm nope, not expected. The error says you tried to call the method using "/dh/dne/image.tiff", can you make sure that job.page.image_path actually matches?

**Comment by bkabrda** [comment]
I copied this issue to the new official repo: https://github.com/bkabrda/flexmock/issues/7 closing this one
