### ISSUE TITLE
Ordered needs to be repeated when using times

### ISSUE THREAD

**Issue by tvuotila** [has207/flexmock#104]
Following doesn't work:

    class String(str):
        pass

    string = String()
    flexmock(string).should_receive('lower').times(2).ordered()
    flexmock(string).should_receive('upper').once().ordered()

    string.lower()
    string.lower()
    string.upper()

Instead you have to write:

    flexmock(string).should_receive('lower').times(2).ordered().ordered()
    flexmock(string).should_receive('upper').once().ordered()

In general, for `.times(N)` you have to repeat `.ordered()` N times.

**Comment by has207** [comment]
Good find! This actually looks pretty hard to fix since times() can be applied after ordered(). This may need a rework of the entire ordered() implementation to get right.

**Comment by bkabrda** [comment]
I copied this issue to the new official repo: https://github.com/bkabrda/flexmock/issues/8 closing this one
