### ISSUE TITLE
Could you release a new version on pypi?

### ISSUE THREAD

**Issue by ghost** [has207/flexmock#108]
I would love to benefit from this commit : 33ae59a76b861d6db7311735c7269cdc9d5b38dc from July 30th

**Comment by lindycoder** [comment]
:+1:

**Comment by bkabrda** [comment]
I've taken over as the new maintainer, the official repo is now at https://github.com/bkabrda/flexmock
I'm planning to release a new version during next week, I'll close this bug for now.
