### ISSUE TITLE
Is it possible to partially mock lambda expressions?

### ISSUE THREAD

**Issue by miquecg** [has207/flexmock#109]
I found a situation where I need to check expectations on a mocked lambda expression returned by another mock object.

The code is more or less like that:

```python
handler = flexmock(lambda: None)

# other mock returns handler
handler\
    .should_receive('__call__')\
    .with_args(DataReceivedEvent)\
    .once()

# exercise code under test
```

Flexmock complains saying: `<function TestDispatchers.test_dispatch_an_event.<locals>.<lambda> at 0x7f8962b03b70> does not have attribute __call__`. AFAIK lambda expressions do have an attribute `__call__` and so are callable.

I'm using Python 3.4.3 and flexmock 0.9.7.

**Comment by miquecg** [comment]
With this code flexmock stops complaining:
```python
class EventHandlerForTests:
    def __call__(self, *args, **kwargs):
        pass

handler = flexmock(EventHandlerForTests)
handler\
    .should_receive('__call__')\
    .with_args(DataReceivedEvent)\
    .once()
```
But however, if I mock **an instance of the class** `EventHandlerForTests`, it fails again.

**Comment by has207** [comment]
So the natural question here would be why in the world would you be trying to mock a lambda? It's an anonymous function, if you can create it to pass to flexmock() you can already make it do whatever you want. If you want a mock object returned then you should just create that directly. Mocking __call__ on an object instance sounds like it should be possible in theory, so that may be a legitimate bug if it only works at the class level.

**Comment by miquecg** [comment]
My apologies if I'm asking something absurd :innocent: . I'm testing a piece of code that it's supposed to dinamically call a function (e.g. `give_me_the_fn()(arg1, arg2)`). After reading [this comment](https://github.com/has207/flexmock/issues/11#issuecomment-674867) I thought it would be better to mock another object rather than the FlexMock class itself and I believed a `lambda` expression was a convenient option.

Maybe it doesn't matter too much in my case because the underlying `__call__` is never invoked, but what if the expectation was `should_call`? Just wondering...

Regarding the differences between mocking `__call__` at class or instance levels I could open a new issue if you wish and close this one if you think it doesn't make sense.

**Comment by miquecg** [comment]
I've arranged some tests in a [gist](https://gist.github.com/miquecg/4c3d8e98314c5fec6a74) for the sake of clarity.

**Comment by bkabrda** [comment]
I copied this issue to the new official repo: https://github.com/bkabrda/flexmock/issues/9 closing this one
