### ISSUE TITLE
Flattr account is restricted

### ISSUE THREAD

**Issue by miquecg** [has207/flexmock#110]
The Flattr button leads to a `400 Bad Request` page saying that the _owner is restricted_.

Link: https://flattr.com/submit/auto?user_id=has207&url=http://github.com/has207&title=flexmock&language=en_GB&tags=github&category=software

**Comment by bkabrda** [comment]
I'm the new maintainer of flexmock and the official repo is now at https://github.com/bkabrda/flexmock; I'll close this, but I'll ping @has207 since he still deserves all the credit!

**Comment by has207** [comment]
I deleted all references to this now, fun to know somebody tried to actually click it :)
