### ISSUE TITLE
Multiple chained stubs sharing a stem are not supported

### ISSUE THREAD

**Issue by nickesk** [has207/flexmock#71]
Flexmock does not handle multiple chained stubs that share the same stem. It appears to only remember the last stub. Example:

```Python
mock = flexmock()
mock.should_receive('get_url.parse_html.retrieve_results').and_return([])
mock.should_receive('get_url.parse_html.retrieve_header').and_return({})
```

The following works:

```Python
mock.get_url().parse_html().retrieve_header()
```

However, the following results in an error:

```Python
mock.get_url().parse_html().retrieve_results()
AttributeError: 'Mock' object has no attribute 'retrieve_results'
```

**Comment by bkabrda** [comment]
I copied this issue to the new official repo: https://github.com/bkabrda/flexmock/issues/1 closing this one
