### ISSUE TITLE
Wrap and proxy method calls for builtin objects rather than error(?)

### ISSUE THREAD

**Issue by has207** [has207/flexmock#82]
It could be useful to do something like the following to ensure all open() calls have a corresponding close(). Unfortunately it's a lot more cumbersome ATM due to inability to directly proxy for instances of builtin objects.

```python

real_open = open
def wrap_open(*k, *kw):
  """ this could be a lambda one-liner even"""
  f = real_open(*k, **kw)
  flexmock(f).should_call('close').with_args().once
  return f

flexmock(__builtins__, open=wrap_open)

**Comment by bkabrda** [comment]
I copied this issue to the new official repo: https://github.com/bkabrda/flexmock/issues/3 closing this one
