### ISSUE TITLE
Class level mock example does not work?

### ISSUE THREAD

**Issue by atacchet** [has207/flexmock#84]
Hi,

Thanks so much for building this library! It's so super useful!!
I cannot execute the code snippet presented here:

http://has207.github.io/flexmock/user-guide.html#class-level-mocks

Maybe the documentation should be amended?
Please let me know if I can provide any further info.

Best,
    Andrea

**Comment by bkabrda** [comment]
I copied this issue to the new official repo: https://github.com/bkabrda/flexmock/issues/4 closing this one
